# Generated by Django 3.2.3 on 2024-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'покупки пользователя',
                'verbose_name_plural': 'Покупки пользователей',
                'ordering': ('recipe', 'user'),
            },
        ),
    ]
