# Generated by Django 3.2.3 on 2024-11-14 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0002_purchaseuser_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddConstraint(
            model_name='purchaseuser',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='Unique purchase constraint'),
        ),
    ]
