MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_NAME_INGREDIENT = 128
MAX_LENGTH_NAME_RECIPE = 256
MAX_LENGTH_SHORT_URL = 6
MAX_LENGTH_TAG = 32
MIN_VALUE = 1

SYMBOLS_FOR_SHORT_URL = (
    'ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz234567890')
