# Generated by Django 5.1.3 on 2024-11-21 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='recipes.recipe', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'покупки пользователя',
                'verbose_name_plural': 'Покупки пользователей',
                'ordering': ('purchase', 'buyer'),
                'constraints': [models.UniqueConstraint(fields=('buyer', 'purchase'), name='Unique purchase constraint')],
            },
        ),
    ]
