# Generated by Django 5.1.3 on 2024-11-21 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_purchaseuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseuser',
            options={'ordering': ('purchase', 'user'), 'verbose_name': 'покупки пользователя', 'verbose_name_plural': 'Покупки пользователей'},
        ),
        migrations.RemoveConstraint(
            model_name='purchaseuser',
            name='Unique purchase constraint',
        ),
        migrations.RenameField(
            model_name='purchaseuser',
            old_name='buyer',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='purchaseuser',
            constraint=models.UniqueConstraint(fields=('user', 'purchase'), name='Unique purchase constraint'),
        ),
    ]
