# Generated by Django 5.1.3 on 2024-11-29 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата публикации'),
            preserve_default=False,
        ),
    ]
