# Generated by Django 3.2.3 on 2024-11-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241117_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(default=None, max_length=6, verbose_name='Короткая ссылка'),
        ),
    ]
