# Generated by Django 3.2.3 on 2024-11-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(auto_created=True, max_length=6, verbose_name='Короткая ссылка'),
        ),
    ]
