# Generated by Django 5.1.3 on 2024-11-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipeingredient_created_at_recipe_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_manager_name': 'tags_and_ingredients', 'default_related_name': 'recipes', 'ordering': ('created_at', 'name'), 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
