# Generated by Django 3.2.3 on 2024-11-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
    ]
