# Generated by Django 3.2.3 on 2024-11-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_url',
        ),
    ]
