# Generated by Django 3.2.3 on 2024-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipe_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
