# Generated by Django 5.1.3 on 2024-11-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipe', 'ordering': ('name', 'id'), 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
