# Generated by Django 5.1.3 on 2024-11-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
    ]
