# Generated by Django 5.1.3 on 2024-11-20 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_bookmarks_bookmarkstag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='рецепт')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='ингредиент')),
            ],
            options={
                'verbose_name': 'ингриsadgдиенты рецепта',
                'verbose_name_plural': 'Ингридиsadherhенты рецептов',
                'ordering': ('bookmark', 'ingredient'),
            },
        ),
    ]
