# Generated by Django 5.1.3 on 2024-11-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_bookmarks_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'default_related_name': 'bookmarks', 'ordering': ('name', 'id'), 'verbose_name': 'рецепssт', 'verbose_name_plural': 'Рецепfffты'},
        ),
    ]
