# Generated by Django 5.1.3 on 2024-11-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_bookmarks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='bookmarks/images/', verbose_name='изображение'),
        ),
    ]
