# Generated by Django 5.1.3 on 2024-11-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_alter_bookmarks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='image',
        ),
    ]
