# Generated by Django 5.1.3 on 2024-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_remove_bookmarks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='image',
            field=models.ImageField(default=None, upload_to='bookmarks/images/', verbose_name='изображение'),
        ),
    ]
