# Generated by Django 5.1.3 on 2024-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('recipes', '0030_bookmarks_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookmarkstag',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='bookmarkstag',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(through='recipes.RecipeTag', to='core.tag'),
        ),
        migrations.DeleteModel(
            name='BookmarkIngredient',
        ),
        migrations.DeleteModel(
            name='Bookmarks',
        ),
        migrations.DeleteModel(
            name='BookmarksTag',
        ),
    ]
