# Generated by Django 5.1.3 on 2024-11-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_remove_bookmarks_author_remove_bookmarkstag_bookmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseuser',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='purchaseuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='PurchaseUser',
        ),
    ]
