# Generated by Django 5.1.3 on 2024-11-20 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_remove_purchaseuser_recipe_remove_purchaseuser_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='recipes.recipe', verbose_name='рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'покупки пользователя',
                'verbose_name_plural': 'Покупки пользователей',
                'ordering': ('recipe', 'user'),
                'constraints': [models.UniqueConstraint(fields=('recipe', 'user'), name='Unique purchase constraint')],
            },
        ),
    ]
