# Generated by Django 5.1.3 on 2024-12-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('following', models.F('user'))), name='Self subscribe constraint'),
        ),
    ]
