# Generated by Django 5.1.3 on 2024-12-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow_self_subscribe_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Self subscribe constraint',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('following', models.F('user')), _negated=True), name='Self subscribe constraint'),
        ),
    ]
