# Generated by Django 5.1.3 on 2024-12-05 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_follow_following_alter_follow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя и Фамилия должны содержать буквенные символы или разрешенные символы `/./- и пробел', regex='^[a-zA-Zа-яА-ЯёЁ\\s\\-\\.\\`]+$')], verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Имя и Фамилия должны содержать буквенные символы или разрешенные символы `/./- и пробел', regex='^[a-zA-Zа-яА-ЯёЁ\\s\\-\\.\\`]+$')], verbose_name='фамилия'),
        ),
    ]
