<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-20 13:59
=======
# Generated by Django 5.1.3 on 2024-11-20 18:23
>>>>>>> 1fcfa77 (back stable version)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ("core", "0001_initial"),
=======
        ('core', '0001_initial'),
>>>>>>> 1fcfa77 (back stable version)
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="подписка",
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
                verbose_name="подписчик",
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "following"), name="Unique follower constraint"
            ),
        ),
    ]
