# Generated by Django 5.1.3 on 2024-11-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_related_name": "tag",
                "ordering": ("name", "id"),
                "verbose_name": "тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
